FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -yq python3 python3-pip debhelper libqt5gui5 && \
    apt-get clean

# RUN apt-get install -y git && \
#     git clone https://github.com/Feelinglight/pyqt_calculator

# WORKDIR /pyqt_calculator

# RUN pip install .

# RUN python3 build_deb.py
