FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -yq python3 python3-pip debhelper libqt5gui5

RUN apt-get install -y python3-pyqt5 zlib1g-dev

RUN pip3 install --no-deps wheel pyinstaller==4.0 pyqt-new-window-handler absresgetter pyqt-resource-helper pyqt-style-setter altgraph pytest

# RUN apt-get install -y git && git clone https://github.com/Feelinglight/pyqt_calculator

# WORKDIR /pyqt_calculator

# RUN python3 build_deb.py
